name: DbApp

on:
  push:
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        target_os: [win-x64, linux-x64]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build for ${{ matrix.target_os }}
        shell: bash 
        run: |
              cd ./db_app
              dotnet publish -c Release -r ${{ matrix.target_os }} --self-contained
              cd ..
              git config --global user.name "${{ secrets.USER_NAME }}"
              git config --global user.email "${{ secrets.USER_EMAIL }}"
              git add .
              git commit -m "${{ matrix.target_os }} build"
              git push