name: DbApp

on:
  push:
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        target_os: [win-x64, linux-x64]

    runs-on: windows-latest

    env:
      WORKING-DIRECTORY: db_app

    steps:
    - name: Build for ${{ matrix.target_os }}
      # run: dotnet publish -c Release -r ${{ matrix.target_os }} --self-contained
      run: ls -a
      working-directory: ${{ env.WORKING-DIRECTORY }}
